### ISSUE TITLE
Cannot change source

### ISSUE THREAD

**Issue by SnippetSpace** [fwestenberg/homeassistant-devialet#6]
Hello,

I have been trying to automate changing my phantom's source to the aux jack when turning on my TV, but this seems to not be possible with this integration. my YAML automations does not seem to be able to trigger a source change.

Here is the snippet that should execute:

```
service: media_player.select_source
data:
  source: Optical jack left
target:
  entity_id: media_player.devialet
```

Is it possible to implement this somehow?
